
package UserView;

import Koneksi.DBKoneksi;
import UserController.UserKeranjang;
import UserController.UserLogin;
import UserController.UserPembayaran;
import UserModel.ModelKeranjang;
import UserModel.ModelPembayaran;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author AGIL
 */
public class UserMenuKeranjang extends javax.swing.JFrame {

    /**
     * Creates new form UserMenuKasir
     */
    public UserMenuKeranjang() {
        initComponents();
        loadKeranjang();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

private void loadKeranjang() {
    try (Connection conn = DBKoneksi.getConnection()) {
        // Ambil user ID dari user yang login
        String userId = UserLogin.getSessionUser().getId();

        // Ambil daftar keranjang user
        List<ModelKeranjang> list = UserKeranjang.getKeranjangPending(conn, userId);

        // Set tabel keranjang
        DefaultTableModel model = (DefaultTableModel) tabelkeranjang.getModel();
        model.setRowCount(0);
        for (ModelKeranjang item : list) {
            model.addRow(new Object[]{
                    item.getNo(),
                    item.getNamaProduk(),
                    item.getKategori(),
                    item.getUkuran(),
                    formatRupiah(item.getHarga()),
                    item.getJumlah(),
                    formatRupiah(item.getSubtotal())
            });
        }

        // Set label info
        int jumlahItem = UserKeranjang.getJumlahItem(conn, userId);
        int totalBarang = UserKeranjang.getTotalBarang(conn, userId);
        long totalHarga = UserKeranjang.getTotalHarga(conn, userId);

        txtjumlahitem.setText("Jumlah Item : " + jumlahItem);
        txttotalbarang.setText("Total Barang : " + totalBarang);
        txttotal.setText("Total : " + formatRupiah(totalHarga));

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat keranjang: " + e.getMessage());
    }
}

    private String formatRupiah(long nominal) {
        java.text.NumberFormat formatter = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("in", "ID"));
        return formatter.format(nominal);
    }
public String cekTransaksiPending(Connection conn, String userId) throws SQLException {
    String sql = """
        SELECT t.id_transaksi 
        FROM transaksi t
        JOIN detail_transaksi dt ON t.id_transaksi = dt.transaksi_id_transaksi
        JOIN pembayaran p ON dt.pembayaran_order_id = p.order_id
        WHERE t.user_id = ? AND p.status = 'pending'
        ORDER BY p.tanggal DESC
        LIMIT 1
    """;

    try (PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, userId);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getString("id_transaksi");
            }
        }
    }
    return null;
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnkembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkeranjang = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtjumlahitem = new javax.swing.JLabel();
        txttotalbarang = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnchekout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("MENU CHECKOUT");

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135)
                .addComponent(btnkembali)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnkembali)
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        tabelkeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Produk  ", "Kategori", "Ukuran ", "Harga", "Jumlah", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelkeranjang.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelkeranjang);
        if (tabelkeranjang.getColumnModel().getColumnCount() > 0) {
            tabelkeranjang.getColumnModel().getColumn(0).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(1).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(2).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(3).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(4).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(5).setResizable(false);
            tabelkeranjang.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        txtjumlahitem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjumlahitem.setText("Jumlah Item");

        txttotalbarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttotalbarang.setText("Total Barang");

        txttotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotal.setText("Total");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txttotalbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtjumlahitem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal)
                    .addComponent(txtjumlahitem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttotalbarang)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btntambah.setText("Tambah Barang");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnupdate.setText("Update Jumlah");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Barang");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnclear.setText("Clear Keranjang");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnchekout.setText("Chekout");
        btnchekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchekoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnchekout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchekout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new UserMenuKasir().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
    String userId = UserLogin.getSessionUser().getId();
    int row = tabelkeranjang.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih dulu barangnya.");
        return;
    }

    try (Connection conn = DBKoneksi.getConnection()) {
        String produkId = UserKeranjang.getProdukIdByRow(conn, userId, row);
        if (produkId == null) {
            JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
            return;
        }

        // Ambil stok dari database
        String sqlStok = "SELECT stok FROM produk WHERE id_produk = ?";
        PreparedStatement pst = conn.prepareStatement(sqlStok);
        pst.setString(1, produkId);
        ResultSet rs = pst.executeQuery();
        int stok = 0;
        if (rs.next()) {
            stok = rs.getInt("stok");
        }

        String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();
        int jumlahSekarang = Integer.parseInt(tabelkeranjang.getValueAt(row, 5).toString());

        if (jumlahSekarang >= stok) {
            JOptionPane.showMessageDialog(this, "Jumlah barang sudah mencapai batas stok.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Tambah 1 barang untuk \"" + namaProduk + "\"?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            UserKeranjang.tambahJumlahBarang(conn, userId, produkId, 1);
            loadKeranjang(); // refresh tampilan
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Kesalahan: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String userId = UserLogin.getSessionUser().getId();
        int row = tabelkeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu produk yang mau diupdate.");
            return;
        }

        String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();

        try (Connection conn = DBKoneksi.getConnection()) {
            String produkId = UserKeranjang.getProdukIdByRow(conn, userId, row);
            if (produkId == null) {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                return;
            }

            // Ambil stok dari produk
            String sql = "SELECT stok FROM produk WHERE id_produk = ?";
            int stok = 0;
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, produkId);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        stok = rs.getInt("stok");
                    } else {
                        JOptionPane.showMessageDialog(this, "Stok produk tidak ditemukan.");
                        return;
                    }
                }
            }

            String input = JOptionPane.showInputDialog(this,
                    "Masukkan jumlah baru untuk \"" + namaProduk + "\" (stok: " + stok + "):");
            if (input == null) return;

            int jumlahBaru;
            try {
                jumlahBaru = Integer.parseInt(input);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Jumlah tidak valid.");
                return;
            }

            if (jumlahBaru <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah tidak boleh nol atau kurang.");
                return;
            }

            if (jumlahBaru > stok) {
                JOptionPane.showMessageDialog(this, "Jumlah melebihi stok. Stok tersedia: " + stok);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Update jumlah produk \"" + namaProduk + "\" menjadi " + jumlahBaru + "?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                UserKeranjang.updateJumlahBarang(conn, userId, produkId, jumlahBaru);
                loadKeranjang();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
    String userId = UserLogin.getSessionUser().getId();

    int row = tabelkeranjang.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Silakan pilih barang yang ingin dihapus.");
        return;
    }

    String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();
    int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus produk '" + namaProduk + "' dari keranjang?",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection conn = DBKoneksi.getConnection()) {
            String produkId = UserKeranjang.getProdukIdByRow(conn, userId, row);
            if (produkId == null) {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                return;
            }

            // Gunakan logika hapusItem yang telah diperbaiki sebelumnya
            UserKeranjang.hapusItem(conn, userId, produkId);
            JOptionPane.showMessageDialog(this, "Produk berhasil dihapus dari keranjang.");
            loadKeranjang();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        String userId = UserLogin.getSessionUser().getId();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus semua item di keranjang?",
                "Konfirmasi Clear Keranjang", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = DBKoneksi.getConnection()) {
                UserKeranjang.cleartransaksi(conn, userId);
                JOptionPane.showMessageDialog(this, "Semua item berhasil dihapus dari keranjang.");
                loadKeranjang();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnchekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchekoutActionPerformed
    try (Connection conn = DBKoneksi.getConnection()) {
        String userId = UserLogin.getSessionUser().getId();
        ModelPembayaran pembayaran = UserPembayaran.getPembayaranPending(conn, userId);

        if (pembayaran == null) {
            JOptionPane.showMessageDialog(this, "Tidak ada transaksi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        new UserMenuPembayaran().setVisible(true);
        dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memeriksa pembayaran.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnchekoutActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchekout;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelkeranjang;
    private javax.swing.JLabel txtjumlahitem;
    private javax.swing.JLabel txttotal;
    private javax.swing.JLabel txttotalbarang;
    // End of variables declaration//GEN-END:variables
}
