/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserView;
import UserModel.ModelSalesReport;

import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.List;
import UserController.UserSalesReport;
import java.io.File;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;




/**
 *
 * @author LAPTOP LENOVO
 */
public class UserMenuLaporan extends javax.swing.JFrame {

    /**
     * Creates new form UserMenuLaporan
     */
     UserSalesReport controller;
     
    public UserMenuLaporan() {
    initComponents();
        viewlaporan.setEditable(false);
        controller = new UserSalesReport(); // inisialisasi controller
        tampilkanLaporan();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
private void tampilkanLaporan() {
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy HH:mm", new Locale("id", "ID"));
    String periode = sdf.format(UserMenuSalesReport.tanggalDipilih);
 

     StringBuilder laporan = new StringBuilder();
    laporan.append("                        LAPORAN KEUANGAN\n\n");
     laporan.append("                       Periode: ").append(periode).append("\n\n");
    laporan.append(String.format("%-15s| %-20s| %-7s| %-9s| %-12s| %-12s\n",
            "ID Transaksi", "Nama Produk", "Jumlah", "Harga", "Total Harga", "Tanggal"));
    laporan.append("-----------------------------------------------------------------------------\n");

    int totalBarang = 0;
    double totalPenjualan = 0;

    UserSalesReport Controller = new UserSalesReport();
    List<ModelSalesReport> list = controller.getSalesReportsByDate(UserMenuSalesReport.tanggalDipilih);

    for (ModelSalesReport sr : list) {
        laporan.append(String.format("%-15s| %-20s| %-7d| %-9.2f| %-12.2f| %-12s\n",
                sr.getID_Transaksi(),
                sr.getNama(),
                sr.getJumlah_barang(),
                sr.getHarga_barang(),
                sr.getTotal_harga(),
                sdf.format(sr.getTanggal_transaksi())));

        totalBarang += sr.getJumlah_barang();
        totalPenjualan += sr.getTotal_harga();
    }

    laporan.append("\nTotal Barang Terjual : ").append(totalBarang);
    laporan.append(String.format("\nTotal Penjualan      : Rp %.2f", totalPenjualan));

    viewlaporan.setFont(new java.awt.Font("Courier New", java.awt.Font.PLAIN, 12));
    viewlaporan.setText(laporan.toString());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewlaporan = new javax.swing.JTextArea();
        btncetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewlaporan.setColumns(20);
        viewlaporan.setRows(5);
        jScrollPane1.setViewportView(viewlaporan);

        btncetak.setText("CETAK PDF");
        btncetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncetakMouseClicked(evt);
            }
        });
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncetak)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Review");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(366, 366, 366))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncetakMouseClicked
    try {
        // Format tanggal jadi nama file
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE-dd-MM-yyyy-HHmmss", new Locale("id", "ID"));
        String periode = sdf.format(UserMenuSalesReport.tanggalDipilih);
        String fileName = "laporan-" + periode + ".pdf";

        // Path ke folder tujuan
        String folderPath = "assets/laporan";
        java.io.File folder = new java.io.File(folderPath);
        if (!folder.exists()) {
            folder.mkdirs(); // buat folder jika belum ada
        }

        String filePath = folderPath + File.separator + fileName;

        // Setup PDF writer
        PdfWriter writer = new PdfWriter(filePath);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        // Judul UserMenuLaporan
        document.add(new Paragraph("LAPORAN KEUANGAN")
            .setFontSize(14)
            .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER));
        document.add(new Paragraph("Periode: " + periode)
            .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER));
        document.add(new Paragraph("\n"));

        // Tabel isi
        com.itextpdf.layout.element.Table table = new com.itextpdf.layout.element.Table(6);
        table.addHeaderCell("ID Transaksi");
        table.addHeaderCell("Nama Produk");
        table.addHeaderCell("Jumlah");
        table.addHeaderCell("Harga");
        table.addHeaderCell("Total Harga");
        table.addHeaderCell("Tanggal");

        int totalBarang = 0;
        double totalPenjualan = 0;
        List<ModelSalesReport> list = controller.getAllSalesReports();

        for (ModelSalesReport sr : list) {
            table.addCell(sr.getID_Transaksi());
            table.addCell(sr.getNama());
            table.addCell(String.valueOf(sr.getJumlah_barang()));
            table.addCell(String.format("Rp %.2f", sr.getHarga_barang()));
            table.addCell(String.format("Rp %.2f", sr.getTotal_harga()));
            table.addCell(sdf.format(sr.getTanggal_transaksi()));

            totalBarang += sr.getJumlah_barang();
            totalPenjualan += sr.getTotal_harga();
        }

        NumberFormat rupiahFormat = NumberFormat.getInstance(new Locale("id", "ID"));

        document.add(table);
        document.add(new Paragraph("\n"));
        document.add(new Paragraph("Total Barang Terjual : " + totalBarang));
        document.add(new Paragraph("Total Penjualan      : Rp " + rupiahFormat.format(totalPenjualan)));

        document.close();
        JOptionPane.showMessageDialog(this, "PDF berhasil disimpan: " + filePath);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal cetak PDF: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btncetakMouseClicked

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea viewlaporan;
    // End of variables declaration//GEN-END:variables
}
