package UserView;

import Koneksi.DBKoneksi;
import UserController.UserLogin;
import java.awt.BorderLayout;
import java.sql.*;
import java.sql.PreparedStatement;
import javax.swing.*;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.sound.sampled.*;

public class UserMenuLinkPembayaran extends javax.swing.JFrame {
    private String redirectUrl;
    private String orderId;
    private JFXPanel jfxPanel;

    public UserMenuLinkPembayaran(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        initComponents();
        setTitle("Pembayaran Midtrans");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        initJavaFX();

        initWebView(redirectUrl);
    }

    private static boolean javafxStarted = false;

    private void initJavaFX() {
      if (!javafxStarted) {
        javafxStarted = true;
        Platform.startup(() -> {
        });
        Platform.setImplicitExit(false);    
      }
    }


    private void initWebView(String url) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());

        jfxPanel = new JFXPanel();
        jPanel1.add(jfxPanel, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();

        Platform.runLater(() -> {
            WebView webView = new WebView();
            WebEngine engine = webView.getEngine();
            engine.load(url);

            engine.locationProperty().addListener((obs, oldUrl, newUrl) -> {
                System.out.println("URL berubah: " + newUrl);
                if (newUrl != null && (newUrl.contains("status_code=200") || newUrl.contains("finish") || newUrl.contains("success"))) {
                    Platform.runLater(this::updateStatusLunas);
                }
            });

            Scene scene = new Scene(webView);
            jfxPanel.setScene(scene);
        });
    }

    private void playSuccessSound() {
        try {
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(
                getClass().getResource("/assets/yippe.wav")); 
            Clip clip = AudioSystem.getClip();
            clip.open(audioInput);
            clip.start();
        } catch (Exception e) {
            System.err.println("Gagal memutar suara notifikasi: " + e.getMessage());
        }
    }

private void updateStatusLunas() {
    try (Connection conn = DBKoneksi.getConnection()) {
        String userId = UserLogin.getSessionUser().getId();

        String sqlPending = """
            SELECT p.order_id
            FROM pembayaran p
            JOIN detail_transaksi dt ON dt.pembayaran_order_id = p.order_id
            JOIN transaksi t ON dt.transaksi_id_transaksi = t.id_transaksi
            WHERE p.status = 'pending' AND t.user_id = ?
            ORDER BY p.tanggal DESC
            LIMIT 1
        """;

        String pendingOrderId = null;
        try (PreparedStatement ps = conn.prepareStatement(sqlPending)) {
            ps.setString(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    pendingOrderId = rs.getString("order_id");
                }
            }
        }

        if (pendingOrderId == null) {
            JOptionPane.showMessageDialog(this,
                "Tidak ada transaksi pending untuk user ini.",
                "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        this.orderId = pendingOrderId;

        try {
            UserController.UserPembayaran.kurangiStokProduk(conn, orderId, userId);

            String sqlUpdate = "UPDATE pembayaran SET status = 'lunas' WHERE order_id = ?";
            try (PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate)) {
                psUpdate.setString(1, orderId);
                int rows = psUpdate.executeUpdate();
                if (rows > 0) {
                    SwingUtilities.invokeLater(() -> {
                        playSuccessSound();
                        JOptionPane.showMessageDialog(this,
                            "Selamat! Pembayaran Anda berhasil.",
                            "Pembayaran Berhasil",
                            JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    });
                }
            }

        } catch (Exception stokException) {
            JOptionPane.showMessageDialog(this,
                "Gagal memproses pembayaran:\n" + stokException.getMessage(),
                "Stok Tidak Cukup",
                JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
