/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserView;

import Koneksi.DBKoneksi;
import UserController.UserLogin;
import UserController.UserPembayaran;
import UserController.UserProduk;
import static UserController.UserProduk.loadProdukTable;
import UserController.UserTransaksi;
import UserModel.ModelPembayaran;
import UserModel.ModelTransaksi;
import javax.swing.JTable;
import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class UserMenuKasir extends javax.swing.JFrame {
    
    public UserMenuKasir () {
        initComponents();
        loadProdukTable(tabelproduk, "");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public JTable getTabelProduk() {
        return this.tabelproduk;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnkeluar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelproduk = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        btnkeranjang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU KASIR");

        btnkeluar1.setText("Keluar");
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(255, 255, 255)
                .addComponent(btnkeluar1)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnkeluar1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tabelproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID Produk", "Nama Produk  ", "Kategori", "Ukuran ", "Harga", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelproduk.getTableHeader().setReorderingAllowed(false);
        tabelproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelprodukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelproduk);
        if (tabelproduk.getColumnModel().getColumnCount() > 0) {
            tabelproduk.getColumnModel().getColumn(0).setResizable(false);
            tabelproduk.getColumnModel().getColumn(1).setResizable(false);
            tabelproduk.getColumnModel().getColumn(2).setResizable(false);
            tabelproduk.getColumnModel().getColumn(3).setResizable(false);
            tabelproduk.getColumnModel().getColumn(4).setResizable(false);
            tabelproduk.getColumnModel().getColumn(5).setResizable(false);
            tabelproduk.getColumnModel().getColumn(6).setResizable(false);
        }

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnkeranjang.setText("Keranjang");
        btnkeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeranjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnkeranjang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1)))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(txtsearch)
                .addGap(18, 18, 18)
                .addComponent(btnreset)
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        new UserView.UserMenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluar1ActionPerformed

    private void tabelprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelprodukMouseClicked
    try (Connection conn = DBKoneksi.getConnection()) {
        int row = tabelproduk.getSelectedRow();
        if (row == -1) return;

        String produkId = tabelproduk.getValueAt(row, 1).toString();
        long harga = Long.parseLong(tabelproduk.getValueAt(row, 5).toString());
        String userId = UserLogin.getSessionUser().getId();

        // Ambil stok produk dari DB
        int stok = 0;
        try (PreparedStatement ps = conn.prepareStatement("SELECT stok FROM produk WHERE id_produk = ?")) {
            ps.setString(1, produkId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                stok = rs.getInt("stok");
            } else {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                return;
            }
        }

        // Ambil jumlah total barang dari user yg BELUM lunas (status pending) untuk produk ini
        int totalSudahDipesan = 0;
        String sqlTotal = """
            SELECT COALESCE(SUM(dt.jumlah_barang), 0) as total 
            FROM detail_transaksi dt
            JOIN transaksi t ON dt.transaksi_id_transaksi = t.id_transaksi
            LEFT JOIN pembayaran p ON dt.pembayaran_order_id = p.order_id
            WHERE t.user_id = ? 
              AND dt.produk_id_produk = ?
              AND (p.status IS NULL OR p.status = 'pending')
        """;
        try (PreparedStatement ps = conn.prepareStatement(sqlTotal)) {
            ps.setString(1, userId);
            ps.setString(2, produkId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                totalSudahDipesan = rs.getInt("total");
            }
        }

        // Input user
        String input = JOptionPane.showInputDialog(this, "Masukkan jumlah yang ingin ditambah:");
        if (input == null || input.isBlank()) return;

        int jumlahBaru = Integer.parseInt(input);
        if (jumlahBaru <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah tidak boleh nol atau negatif.");
            return;
        }

        int totalSetelahInput = totalSudahDipesan + jumlahBaru;
        if (totalSetelahInput > stok) {
            JOptionPane.showMessageDialog(this, """
                Jumlah melebihi stok!
                Sudah dipesan: %d
                Ingin tambah: %d
                Stok tersedia: %d
                Sisa yang bisa ditambah: %d
                """.formatted(totalSudahDipesan, jumlahBaru, stok, stok - totalSudahDipesan));
            return;
        }

        // Cari transaksi pending (jika ada)
        String idTransaksi = null;
        String sqlTransaksi = """
            SELECT t.id_transaksi
            FROM transaksi t
            JOIN detail_transaksi dt ON t.id_transaksi = dt.transaksi_id_transaksi
            JOIN pembayaran p ON dt.pembayaran_order_id = p.order_id
            WHERE p.status = 'pending' AND t.user_id = ?
            LIMIT 1
        """;
        try (PreparedStatement ps = conn.prepareStatement(sqlTransaksi)) {
            ps.setString(1, userId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                idTransaksi = rs.getString("id_transaksi");
            }
        }

        if (idTransaksi == null) {
            idTransaksi = UserTransaksi.generateIdTransaksi(conn, userId);
        }

        // Cek apakah produk sudah ada dalam transaksi pending ini
        boolean sudahAda = false;
        int jumlahLama = 0;
        String sqlCek = """
            SELECT jumlah_barang FROM detail_transaksi 
            WHERE transaksi_id_transaksi = ? AND produk_id_produk = ? AND pembayaran_order_id IS NULL
        """;
        try (PreparedStatement ps = conn.prepareStatement(sqlCek)) {
            ps.setString(1, idTransaksi);
            ps.setString(2, produkId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                jumlahLama = rs.getInt("jumlah_barang");
                sudahAda = true;
            }
        }

        if (sudahAda) {
            String sqlUpdate = """
                UPDATE detail_transaksi
                SET jumlah_barang = ?, total_harga = ?
                WHERE transaksi_id_transaksi = ? AND produk_id_produk = ? AND pembayaran_order_id IS NULL
            """;
            try (PreparedStatement ps = conn.prepareStatement(sqlUpdate)) {
                ps.setInt(1, jumlahLama + jumlahBaru);
                ps.setLong(2, harga * (jumlahLama + jumlahBaru));
                ps.setString(3, idTransaksi);
                ps.setString(4, produkId);
                ps.executeUpdate();
            }
        } else {
            ModelTransaksi transaksi = new ModelTransaksi();
            transaksi.setIdTransaksi(idTransaksi);
            transaksi.setTanggalTransaksi(new Date());
            transaksi.setUserId(userId);
            transaksi.setProdukId(produkId);
            transaksi.setHarga(harga);
            transaksi.setJumlahBarang(jumlahBaru);
            transaksi.setTotalHarga(harga * jumlahBaru);
            transaksi.setTotalPembayaran(harga * jumlahBaru);
            UserTransaksi.buatTransaksi(conn, transaksi);
        }

        JOptionPane.showMessageDialog(this, "Berhasil ditambahkan ke transaksi: " + idTransaksi);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_tabelprodukMouseClicked

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
    txtsearch.setText("");
    UserProduk.loadProdukTable(tabelproduk, null);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnkeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeranjangActionPerformed
    try (Connection conn = DBKoneksi.getConnection()) {
        String userId = UserLogin.getSessionUser().getId();
        ModelPembayaran pembayaran = UserPembayaran.getPembayaranPending(conn, userId);

        if (pembayaran == null) {
            JOptionPane.showMessageDialog(this, "Tidak ada transaksi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        new UserMenuKeranjang().setVisible(true);
        dispose();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memeriksa pembayaran.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnkeranjangActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
    String keyword = txtsearch.getText().trim();
    UserProduk.loadProdukTable(tabelproduk, keyword); 
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnkeranjang;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelproduk;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
