/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerView;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.sql.Timestamp;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
/**
 *
 * @author AGIL
 */
public class CustomerHistory extends javax.swing.JPanel {

    /**
     * Creates new form History
     */
    public CustomerHistory() {
        initComponents();
            tampilkanRiwayatTransaksi();
            
    }
    
private void tampilkanRiwayatTransaksi() {
    jPanel2.removeAll();
    jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));

    List<Map<String, Object>> daftarRiwayat = new ArrayList<>();

    try {
        String idCustomer = CustomerController.CustomerLogin.sessionCustomer.getId();
        Connection conn = Koneksi.DBKoneksi.getConnection();
        String sql = """
            SELECT DISTINCT t.id_transaksi, t.tanggal_transaksi
            FROM transaksi t
            JOIN detail_transaksi d ON t.id_transaksi = d.transaksi_id_transaksi
            JOIN pembayaran b ON d.pembayaran_order_id = b.order_id
            WHERE t.customer_id = ? AND b.status = 'lunas'
            ORDER BY t.tanggal_transaksi DESC
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idCustomer);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Map<String, Object> data = new HashMap<>();
            data.put("id_transaksi", rs.getString("id_transaksi"));
            data.put("tanggal_transaksi", rs.getTimestamp("tanggal_transaksi"));
            daftarRiwayat.add(data);
        }

        rs.close();
        ps.close();
        conn.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat riwayat transaksi");
    }

    if (daftarRiwayat.isEmpty()) {
        JLabel lblTidakDitemukan = new JLabel("Belum ada riwayat transaksi.");
        lblTidakDitemukan.setFont(new Font("Arial", Font.BOLD, 16));
        lblTidakDitemukan.setForeground(Color.GRAY);
        lblTidakDitemukan.setAlignmentX(Component.CENTER_ALIGNMENT);

        jPanel2.add(Box.createVerticalGlue());
        jPanel2.add(lblTidakDitemukan);
        jPanel2.add(Box.createVerticalGlue());
    } else {
        for (Map<String, Object> riwayat : daftarRiwayat) {
            String idTransaksi = (String) riwayat.get("id_transaksi");
            Timestamp tanggal = (Timestamp) riwayat.get("tanggal_transaksi");

            CustomerBingkaiHistory panel = new CustomerBingkaiHistory(idTransaksi, tanggal);
            panel.setAlignmentX(Component.LEFT_ALIGNMENT);
            jPanel2.add(panel);
            jPanel2.add(Box.createVerticalStrut(10));
        }
    }

    jPanel2.revalidate();
    jPanel2.repaint();
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RIWAYAT TRANSAKSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(270, 270, 270))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
