/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerView;

import CustomerController.CustomerStruk;
import CustomerView.CustomerStrukCustomer;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.Locale;
import javax.swing.JTable;

/**
 * Panel untuk menampilkan detail riwayat transaksi.
 * @author AGIL
 */
public class CustomerBingkaiHistory extends javax.swing.JPanel {
        private String orderId;


    public CustomerBingkaiHistory(String idTransaksi, Timestamp tanggal) {
        initComponents();
        loadDataTransaksi(idTransaksi, tanggal);
    }

private void loadDataTransaksi(String idTransaksi, Timestamp tanggal) {
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMM yyyy HH:mm", new Locale("id", "ID"));
    txttanggal.setText("Tanggal: " + sdf.format(tanggal));

    DefaultTableModel model = (DefaultTableModel) tablehistory.getModel();
    model.setRowCount(0); // Bersihkan isi tabel

    try {
        Connection conn = Koneksi.DBKoneksi.getConnection();
        String sql = """
            SELECT d.pembayaran_order_id, p.nama, d.jumlah_barang, d.harga, 
                   d.total_harga, b.metode_pembayaran, b.status
            FROM detail_transaksi d
            JOIN produk p ON d.produk_id_produk = p.id_produk
            LEFT JOIN pembayaran b ON d.pembayaran_order_id = b.order_id
            WHERE d.transaksi_id_transaksi = ?
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idTransaksi);
        ResultSet rs = ps.executeQuery();

        boolean isFirstRow = true;

        while (rs.next()) {
            String currentOrderId = rs.getString("pembayaran_order_id");

            if (isFirstRow) {
                this.orderId = currentOrderId;
                isFirstRow = false;
            }

            model.addRow(new Object[]{
                idTransaksi,
                currentOrderId,
                rs.getString("nama"),
                rs.getInt("jumlah_barang"),
                rs.getLong("harga"),
                rs.getLong("total_harga"),
                rs.getString("metode_pembayaran"),
                rs.getString("status")
            });
        }

        rs.close();
        ps.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data transaksi:\n" + e.getMessage());
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablehistory = new javax.swing.JTable();
        txttanggal = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tablehistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaksi ID", "Order ID", "Nama Produk", "Jumlah", "Harga", "Sub Total", "Pembayaran", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablehistory.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablehistory);
        if (tablehistory.getColumnModel().getColumnCount() > 0) {
            tablehistory.getColumnModel().getColumn(0).setResizable(false);
            tablehistory.getColumnModel().getColumn(1).setResizable(false);
            tablehistory.getColumnModel().getColumn(2).setResizable(false);
            tablehistory.getColumnModel().getColumn(3).setResizable(false);
            tablehistory.getColumnModel().getColumn(4).setResizable(false);
            tablehistory.getColumnModel().getColumn(5).setResizable(false);
            tablehistory.getColumnModel().getColumn(6).setResizable(false);
            tablehistory.getColumnModel().getColumn(7).setResizable(false);
        }

        txttanggal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txttanggal.setText("Tanggal Transaksi");

        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(449, 449, 449)
                        .addComponent(btnprint))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttanggal)
                    .addComponent(btnprint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
    try (Connection conn = Koneksi.DBKoneksi.getConnection()) {
        String isiStruk = CustomerStruk.generateIsiStrukCustomer(conn, orderId);

        String path = "assets/struk/struk" + orderId + ".pdf";
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(path));
        document.open();
        com.itextpdf.text.Font font = com.itextpdf.text.FontFactory.getFont(
                com.itextpdf.text.FontFactory.COURIER, 12, com.itextpdf.text.BaseColor.BLACK);
        document.add(new com.itextpdf.text.Paragraph(isiStruk, font));
        document.close();

        new CustomerStrukCustomer(orderId).setVisible(true);

        JOptionPane.showMessageDialog(this, "PDF struk berhasil disimpan di:\n" + path);

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal menyimpan PDF:\n" + ex.getMessage());
    }
    }//GEN-LAST:event_btnprintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablehistory;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
