/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerView;

import CustomerController.CustomerGoogleLogin;
import CustomerController.CustomerLogin;
import java.awt.geom.RoundRectangle2D;
import static javafx.application.Platform.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author hp5cd
 */
public class CustomerMenuLogin extends javax.swing.JFrame {
    private int mouseX;
    private int mouseY;
    /**
     * Creates new form CustomerLogin
     */
    public CustomerMenuLogin() {
        setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        ib_hide.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new CustomUI.PanelRound();
        ib_hide = new javax.swing.JLabel();
        ib_show = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new CustomUI.PasswordFieldCustom();
        txtusername = new CustomUI.TextFieldCustom();
        login = new CustomUI.Button();
        logingoogle = new CustomUI.ButtonOutLine();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnregister = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelGradient1 = new CustomUI.PanelGradient();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ib_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_invisible_24px.png"))); // NOI18N
        ib_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ib_hideMouseClicked(evt);
            }
        });
        panelRound1.add(ib_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 254, 30, 30));

        ib_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_eye_24px.png"))); // NOI18N
        ib_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ib_showMouseClicked(evt);
            }
        });
        panelRound1.add(ib_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 20));

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("LOGIN");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        panelRound1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 253, 220, 30));

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        panelRound1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 174, 220, 30));

        login.setBackground(new java.awt.Color(0, 153, 255));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        panelRound1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 200, -1));

        logingoogle.setBackground(new java.awt.Color(0, 0, 0));
        logingoogle.setForeground(new java.awt.Color(153, 153, 153));
        logingoogle.setText("Sign In with Google");
        logingoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logingoogleActionPerformed(evt);
            }
        });
        panelRound1.add(logingoogle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 200, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jLabel3.setText("Username");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel4.setText("Password");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        btnregister.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnregister.setForeground(new java.awt.Color(153, 153, 153));
        btnregister.setText("Sign Up");
        btnregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregisterMouseClicked(evt);
            }
        });
        panelRound1.add(btnregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_google_24px.png"))); // NOI18N
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Don't have an account?  ");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Hello, Welcome Back");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cancel_28px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        panelGradient1.setColor2(new java.awt.Color(102, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Modern T-Shirt Sale Instagram Post (500 x 500 piksel).png"))); // NOI18N

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void logingoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logingoogleActionPerformed
        if (CustomerGoogleLogin.loginDenganGoogleLangsung()) {
            new CustomerHomeCustomer().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login dengan Google gagal.");
        }
    }//GEN-LAST:event_logingoogleActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void ib_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ib_showMouseClicked
        ib_show.setVisible(false);
        ib_hide.setVisible(true);
        txtpassword.setEchoChar((char)0);
    }//GEN-LAST:event_ib_showMouseClicked

    private void ib_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ib_hideMouseClicked
        ib_show.setVisible(true);
        ib_hide.setVisible(false);
        txtpassword.setEchoChar('*');
    }//GEN-LAST:event_ib_hideMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
      String username = txtusername.getText().trim();
    String password = new String(txtpassword.getPassword()).trim();

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan password tidak boleh kosong.");
        return;
    }

    String hashedPassword = CustomerLogin.hashPassword(password);

    boolean success = CustomerController.CustomerLogin.login(username, hashedPassword);

    if (success) {
        new CustomerHomeCustomer().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_loginActionPerformed

    private void btnregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregisterMouseClicked
        new CustomerSignUp().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregisterMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dispose();
        exit();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnregister;
    private javax.swing.JLabel ib_hide;
    private javax.swing.JLabel ib_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private CustomUI.Button login;
    private CustomUI.ButtonOutLine logingoogle;
    private CustomUI.PanelGradient panelGradient1;
    private CustomUI.PanelRound panelRound1;
    private CustomUI.PasswordFieldCustom txtpassword;
    private CustomUI.TextFieldCustom txtusername;
    // End of variables declaration//GEN-END:variables
}
