/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerView;

import CustomerController.CustomerLogin;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author hp5cd
 */
public class CustomerHomeCustomer extends javax.swing.JFrame {
    private static CustomerHomeCustomer instance;
    private JPanel panelAktif;


    public CustomerHomeCustomer() {
        instance = this; 
        setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        dt();     
        times();  
        menupertama();
        lbnamacustomer.setText("Selamat Datang, " + CustomerLogin.sessionCustomer.getUsername());
    }
        public static CustomerHomeCustomer getInstance() {
        return instance;
    }
    
    
    public void tampilkanTransaksiCustomer() {
    pn_utama.removeAll();
    pn_utama.add(new TransaksiCustomer());
    pn_utama.revalidate();
    pn_utama.repaint();
}
    
 
public void refreshSetelahBayar() {
    try {
        if (panelAktif instanceof TransaksiCustomer) {
            tampilkanTransaksiCustomer(); // Reload
        } else if (panelAktif instanceof CustomerProduk) {
            menupertama();
        } else {
            System.out.println("Panel aktif tidak dikenali atau belum disetting.");
        }

        System.out.println("Panel berhasil direfresh setelah pembayaran.");
    } catch (Exception e) {
        e.printStackTrace();
    }
}





    private void menupertama(){
        pn_utama.removeAll();
        pn_utama.add(new CustomerProduk());
        
        pn_utama.repaint();
        pn_utama.revalidate();  
    }

    private void dt() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy",new Locale("id", "ID"));
        hari.setText(sdf.format(now));
    }

    private void times() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                waktu.setText(sdf.format(date));
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOutLine1 = new CustomUI.ButtonOutLine();
        pn_kiri = new CustomUI.PanelGradient1();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn_main1 = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        btn_produk = new javax.swing.JLabel();
        pn_main2 = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        btn_transaksi = new javax.swing.JLabel();
        pn_main3 = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        btn_dashboard3 = new javax.swing.JLabel();
        pn_main5 = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        btn_keluar = new javax.swing.JLabel();
        lbnamacustomer = new javax.swing.JLabel();
        pn_utama = new javax.swing.JPanel();
        panelGradient11 = new CustomUI.PanelGradient1();
        hari = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();

        buttonOutLine1.setText("buttonOutLine1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_kiri.setColorStart(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_administrator_male_50px.png"))); // NOI18N
        jLabel1.setText("KemejaSalatiga");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("LAINNYA");

        pn_main1.setBackground(new java.awt.Color(255, 255, 255));
        pn_main1.setForeground(new java.awt.Color(102, 102, 102));
        pn_main1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main1MouseEntered(evt);
            }
        });

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_produk.setBackground(new java.awt.Color(102, 102, 102));
        btn_produk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_produk.setForeground(new java.awt.Color(153, 153, 153));
        btn_produk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_edit_product_28px.png"))); // NOI18N
        btn_produk.setText("PRODUCT");
        btn_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_produkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_produkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_produkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main1Layout = new javax.swing.GroupLayout(pn_main1);
        pn_main1.setLayout(pn_main1Layout);
        pn_main1Layout.setHorizontalGroup(
            pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pn_main1Layout.setVerticalGroup(
            pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_main1Layout.createSequentialGroup()
                        .addComponent(btn_produk)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn_line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_main2.setBackground(new java.awt.Color(255, 255, 255));
        pn_main2.setForeground(new java.awt.Color(102, 102, 102));
        pn_main2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main2MouseEntered(evt);
            }
        });

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_transaksi.setBackground(new java.awt.Color(102, 102, 102));
        btn_transaksi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(153, 153, 153));
        btn_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_buy_for_change_28px.png"))); // NOI18N
        btn_transaksi.setText("TRANSACTION");
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main2Layout = new javax.swing.GroupLayout(pn_main2);
        pn_main2.setLayout(pn_main2Layout);
        pn_main2Layout.setHorizontalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        pn_main2Layout.setVerticalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_main3.setBackground(new java.awt.Color(255, 255, 255));
        pn_main3.setForeground(new java.awt.Color(102, 102, 102));
        pn_main3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main3MouseEntered(evt);
            }
        });

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_dashboard3.setBackground(new java.awt.Color(102, 102, 102));
        btn_dashboard3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_dashboard3.setForeground(new java.awt.Color(153, 153, 153));
        btn_dashboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_pie_chart_report_28px.png"))); // NOI18N
        btn_dashboard3.setText("REPORT");
        btn_dashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboard3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboard3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboard3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main3Layout = new javax.swing.GroupLayout(pn_main3);
        pn_main3.setLayout(pn_main3Layout);
        pn_main3Layout.setHorizontalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_main3Layout.setVerticalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_main3Layout.createSequentialGroup()
                        .addComponent(btn_dashboard3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn_line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_main5.setBackground(new java.awt.Color(255, 255, 255));
        pn_main5.setForeground(new java.awt.Color(102, 102, 102));
        pn_main5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_main5MouseEntered(evt);
            }
        });

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_keluar.setBackground(new java.awt.Color(102, 102, 102));
        btn_keluar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(153, 153, 153));
        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_logout_rounded_left_28px.png"))); // NOI18N
        btn_keluar.setText("LOGOUT");
        btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_keluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_keluarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_main5Layout = new javax.swing.GroupLayout(pn_main5);
        pn_main5.setLayout(pn_main5Layout);
        pn_main5Layout.setHorizontalGroup(
            pn_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
        );
        pn_main5Layout.setVerticalGroup(
            pn_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_main5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_main5Layout.createSequentialGroup()
                        .addComponent(btn_keluar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn_line5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbnamacustomer.setText("jLabel2");

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_main5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pn_main3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_main1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbnamacustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbnamacustomer)
                .addGap(35, 35, 35)
                .addComponent(pn_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pn_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(pn_main5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 200, 650));

        pn_utama.setBackground(new java.awt.Color(204, 204, 204));
        pn_utama.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pn_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 930, 600));

        panelGradient11.setColorEnd(new java.awt.Color(0, 0, 255));
        panelGradient11.setColorStart(new java.awt.Color(0, 204, 204));

        hari.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hari.setForeground(new java.awt.Color(255, 255, 255));
        hari.setText("0");

        waktu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("0");

        javax.swing.GroupLayout panelGradient11Layout = new javax.swing.GroupLayout(panelGradient11);
        panelGradient11.setLayout(panelGradient11Layout);
        panelGradient11Layout.setHorizontalGroup(
            panelGradient11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient11Layout.createSequentialGroup()
                .addContainerGap(812, Short.MAX_VALUE)
                .addComponent(hari)
                .addGap(58, 58, 58)
                .addComponent(waktu)
                .addGap(54, 54, 54))
        );
        panelGradient11Layout.setVerticalGroup(
            panelGradient11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient11Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panelGradient11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hari)
                    .addComponent(waktu))
                .addContainerGap())
        );

        getContentPane().add(panelGradient11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 940, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseClicked
        pn_main1.setBackground(new Color(0, 204, 204));
        pn_line1.setBackground(new Color(0, 102, 153));

        pn_utama.removeAll();
        pn_utama.add(new CustomerProduk());
        
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_produkMouseClicked

    private void btn_produkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseEntered
        pn_main1.setBackground(new Color(204, 255, 255));
        pn_line1.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_produkMouseEntered

    private void btn_produkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produkMouseExited
    pn_main1.setBackground(new Color(255, 255, 255));
    pn_line1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_produkMouseExited

    private void pn_main1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main1MouseEntered

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        pn_main2.setBackground(new Color(0, 204, 204));
        pn_line2.setBackground(new Color(0, 102, 153));
        
        pn_utama.removeAll();
        pn_utama.add(new TransaksiCustomer());
        
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        pn_main2.setBackground(new Color(204, 255, 255));
        pn_line2.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseExited
        pn_main2.setBackground(new Color(255, 255, 255));
        pn_line2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_transaksiMouseExited

    private void pn_main2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main2MouseEntered

    private void btn_dashboard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard3MouseClicked
        pn_main3.setBackground(new Color(0, 204, 204));
        pn_line3.setBackground(new Color(0, 102, 153));

        pn_utama.removeAll();
        pn_utama.add(new CustomerHistory());
        
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboard3MouseClicked

    private void btn_dashboard3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard3MouseEntered
        pn_main3.setBackground(new Color(204, 255, 255));
        pn_line3.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_dashboard3MouseEntered

    private void btn_dashboard3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboard3MouseExited
        pn_main3.setBackground(new Color(255, 255, 255));
        pn_line3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_dashboard3MouseExited

    private void pn_main3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main3MouseEntered

    private void btn_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseClicked
// Ubah warna navigasi (highlight button)
    pn_main5.setBackground(new Color(0, 204, 204));
    pn_line5.setBackground(new Color(0, 102, 153));

    // Tutup frame utama
    dispose(); // langsung dispose jendela saat ini
    new CustomerMenuLogin().setVisible(true); // buka kembali form login
    }//GEN-LAST:event_btn_keluarMouseClicked

    private void btn_keluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseEntered
        pn_main5.setBackground(new Color(204, 255, 255));
        pn_line5.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_keluarMouseEntered

    private void btn_keluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseExited
        pn_main5.setBackground(new Color(255, 255, 255));
        pn_line5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_keluarMouseExited

    private void pn_main5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_main5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pn_main5MouseEntered

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_dashboard3;
    private javax.swing.JLabel btn_keluar;
    private javax.swing.JLabel btn_produk;
    private javax.swing.JLabel btn_transaksi;
    private CustomUI.ButtonOutLine buttonOutLine1;
    private javax.swing.JLabel hari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbnamacustomer;
    private CustomUI.PanelGradient1 panelGradient11;
    private CustomUI.PanelGradient1 pn_kiri;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_main1;
    private javax.swing.JPanel pn_main2;
    private javax.swing.JPanel pn_main3;
    private javax.swing.JPanel pn_main5;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
