/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerView;

import CustomerController.CustomerLogin;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author hp5cd
 */
public class CustomerSignUp extends javax.swing.JFrame {
      private int mouseX;
      private int mouseY;
    /**
     * Creates new form NewJFrame
     */
    public CustomerSignUp() {
        setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        ib_hide.setVisible(false);
        reset();
    }
    
private void reset(){
    lbperingatanusername.setText("");
    lbperingatanpassword.setText("");
    lbperingatankonfirmasipassword.setText("");
    lbperingatanemail.setText("");
    lbperingatanalamat.setText(""); 
}

private boolean validasiInput(String username, String password, String konfirmasiPassword, String email, String alamat) {
    boolean valid = true;    

    if (username.trim().isEmpty()) {
        lbperingatanusername.setText("Username harus diisi");
        valid = false;
    } else if (!username.matches("[a-zA-Z]+")) {
        lbperingatanusername.setText("Username hanya huruf");
        valid = false;
    } else if (CustomerLogin.isUsernameExist(username)) {
        lbperingatanusername.setText("Username sudah digunakan");
        valid = false;
    }

    if (password.trim().isEmpty()) {
        lbperingatanpassword.setText("Password harus diisi");
        valid = false;
    } else if (password.length() < 8 || password.length() > 16) {
        lbperingatanpassword.setText("Password harus 8-16 karakter");
        valid = false;
    }

    if (konfirmasiPassword.trim().isEmpty()) {
        lbperingatankonfirmasipassword.setText("Konfirmasi harus diisi");
        valid = false;
    } else if (!password.equals(konfirmasiPassword)) {
        lbperingatankonfirmasipassword.setText("Konfirmasi tidak sama");
        valid = false;
    }


    if (email.trim().isEmpty()) {
        lbperingatanemail.setText("Email harus diisi");
        valid = false;
    } else if (!email.endsWith("@gmail.com")) {
        lbperingatanemail.setText("Email harus @gmail.com");
        valid = false;
    } else if (CustomerLogin.isEmailExist(email)) {
        lbperingatanemail.setText("Email sudah digunakan");
        valid = false;
    }

    if (alamat.trim().isEmpty()) {
        lbperingatanalamat.setText("Alamat harus diisi");
        valid = false;
    } else if (alamat.length() > 200) {
        lbperingatanalamat.setText("Alamat maksimal 200 karakter");
        valid = false;
    }

    return valid;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelRound1 = new CustomUI.PanelRound();
        ib_hide = new javax.swing.JLabel();
        ib_show = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new CustomUI.PasswordFieldCustom();
        txtusername = new CustomUI.TextFieldCustom();
        txtemail = new CustomUI.TextFieldCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsignup = new CustomUI.Button();
        jLabel7 = new javax.swing.JLabel();
        txtkonfrimasipassword = new CustomUI.PasswordFieldCustom();
        txtalamat = new CustomUI.TextFieldCustom();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbperingatanusername = new javax.swing.JLabel();
        lbperingatanalamat = new javax.swing.JLabel();
        lbperingatanemail = new javax.swing.JLabel();
        lbperingatanpassword = new javax.swing.JLabel();
        lbperingatankonfirmasipassword = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelGradient11 = new CustomUI.PanelGradient1();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(100);
        panelRound1.setRoundTopLeft(100);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ib_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_invisible_24px.png"))); // NOI18N
        ib_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ib_hideMouseClicked(evt);
            }
        });
        panelRound1.add(ib_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 40, 30));

        ib_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_eye_24px.png"))); // NOI18N
        ib_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ib_showMouseClicked(evt);
            }
        });
        panelRound1.add(ib_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 40, 30));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Create Your Account");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 30));

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        panelRound1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 250, 31));

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        panelRound1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, 31));
        panelRound1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 250, 30));

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("SIGN UP");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jLabel1.setText("Username");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel4.setText("Konfirmasi Password");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jLabel5.setText("Email");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        btnsignup.setBackground(new java.awt.Color(51, 153, 255));
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("SIGN UP");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        panelRound1.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 180, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        jLabel7.setText("Password");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtkonfrimasipassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkonfrimasipasswordActionPerformed(evt);
            }
        });
        panelRound1.add(txtkonfrimasipassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 250, 31));
        panelRound1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 250, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_country_house_24px.png"))); // NOI18N
        jLabel9.setText("Alamat");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_24px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 30));

        lbperingatanusername.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbperingatanusername.setForeground(new java.awt.Color(255, 51, 51));
        lbperingatanusername.setText("*Peringatan Username Harus Diisi");
        panelRound1.add(lbperingatanusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 20));

        lbperingatanalamat.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbperingatanalamat.setForeground(new java.awt.Color(255, 51, 51));
        lbperingatanalamat.setText("*Peringatan Alamat Harus Diisi");
        panelRound1.add(lbperingatanalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        lbperingatanemail.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbperingatanemail.setForeground(new java.awt.Color(255, 51, 51));
        lbperingatanemail.setText("*Peringatan Email Harus Diisi");
        panelRound1.add(lbperingatanemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        lbperingatanpassword.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbperingatanpassword.setForeground(new java.awt.Color(255, 51, 51));
        lbperingatanpassword.setText("*Peringatan Password Harus Diisi");
        panelRound1.add(lbperingatanpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        lbperingatankonfirmasipassword.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lbperingatankonfirmasipassword.setForeground(new java.awt.Color(255, 51, 51));
        lbperingatankonfirmasipassword.setText("*Peringatan Konfirmasi Password Harus Diisi");
        panelRound1.add(lbperingatankonfirmasipassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Back to Login?");
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, 20));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Sign in");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 409, -1, 40));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 540, 460));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange & White Gradient Grunge Sculpture Illustrative T-shirt (1).png"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout panelGradient11Layout = new javax.swing.GroupLayout(panelGradient11);
        panelGradient11.setLayout(panelGradient11Layout);
        panelGradient11Layout.setHorizontalGroup(
            panelGradient11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient11Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGradient11Layout.setVerticalGroup(
            panelGradient11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient11Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelGradient11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
    reset();
    
    String username = txtusername.getText();
    String password = new String(txtpassword.getPassword());
    String konfirmasi = new String(txtkonfrimasipassword.getPassword());
    String email = txtemail.getText();
    String alamat = txtalamat.getText();

    if (validasiInput(username, password, konfirmasi, email, alamat)) {
        String hashedPassword = CustomerLogin.hashPassword(password);
        String hashedKonfirmasi = CustomerLogin.hashPassword(konfirmasi);

        boolean success = CustomerLogin.daftarCustomerBaru(username, hashedPassword, hashedKonfirmasi, email, alamat);
        if (success) {
            JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!");
            new CustomerMenuLogin().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pendaftaran gagal.");
        }
    }
    }//GEN-LAST:event_btnsignupActionPerformed

    private void ib_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ib_hideMouseClicked
        ib_show.setVisible(true);
        ib_hide.setVisible(false);
        txtkonfrimasipassword.setEchoChar('*');
        
    }//GEN-LAST:event_ib_hideMouseClicked

    private void ib_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ib_showMouseClicked
        ib_show.setVisible(false);
        ib_hide.setVisible(true);
        txtkonfrimasipassword.setEchoChar((char)0);
    }//GEN-LAST:event_ib_showMouseClicked

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtkonfrimasipasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkonfrimasipasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfrimasipasswordActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
            new CustomerMenuLogin().show();
            dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomUI.Button btnsignup;
    private javax.swing.JLabel ib_hide;
    private javax.swing.JLabel ib_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbperingatanalamat;
    private javax.swing.JLabel lbperingatanemail;
    private javax.swing.JLabel lbperingatankonfirmasipassword;
    private javax.swing.JLabel lbperingatanpassword;
    private javax.swing.JLabel lbperingatanusername;
    private CustomUI.PanelGradient1 panelGradient11;
    private CustomUI.PanelRound panelRound1;
    private CustomUI.TextFieldCustom txtalamat;
    private CustomUI.TextFieldCustom txtemail;
    private CustomUI.PasswordFieldCustom txtkonfrimasipassword;
    private CustomUI.PasswordFieldCustom txtpassword;
    private CustomUI.TextFieldCustom txtusername;
    // End of variables declaration//GEN-END:variables
}
