/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerView;

import Koneksi.DBKoneksi;
import CustomerController.CustomerLogin;
import CustomerController.CustomerTransaksiOnline;
import CustomerModel.CustomerModelBingkai;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author AGIL
 */
public class CustomerBingkaiProdukOnline extends javax.swing.JPanel {

    /**
     * Creates new form BingkaiProdukOnline
     */
    public CustomerBingkaiProdukOnline() {
        initComponents();
        aturLayout();
    }
    
    private void aturLayout() {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(Box.createVerticalStrut(10));
        add(lbgambar);
        add(Box.createVerticalStrut(10));
        add(lbnama);
        add(Box.createVerticalStrut(5));
        add(lbharga);
        add(Box.createVerticalStrut(5));
        add(lbstok);
        add(Box.createVerticalStrut(10));
        add(btnbeli);
        lbgambar.setAlignmentX(CENTER_ALIGNMENT);
        lbnama.setAlignmentX(CENTER_ALIGNMENT);
        lbharga.setAlignmentX(CENTER_ALIGNMENT);
        lbstok.setAlignmentX(CENTER_ALIGNMENT);
        btnbeli.setAlignmentX(CENTER_ALIGNMENT);
    }
    
public void setData(CustomerModelBingkai model) {
    lbnama.setText(model.getNamaProduk());
    lbharga.setText("Rp " + model.getHarga());
    lbstok.setText("Stok: " + model.getStok());

    ImageIcon icon = model.getGambar();

    try {
        int stok = Integer.parseInt(model.getStok());
        if (stok == 0) {
            // Gambar dibuat transparan
            Image transparan = buatGambarTransparan(icon.getImage(), 0.3f);
            icon = new ImageIcon(transparan);

            // Nonaktifkan tombol beli
            btnbeli.setEnabled(false);

            // Teks dibuat abu-abu
            lbnama.setForeground(Color.GRAY);
            lbharga.setForeground(Color.GRAY);
            lbstok.setForeground(Color.GRAY);

            setBackground(new Color(230, 230, 230)); // latar pudar
        } else {
            // Gambar normal
            btnbeli.setEnabled(true);
            lbnama.setForeground(Color.BLACK);
            lbharga.setForeground(Color.BLACK);
            lbstok.setForeground(Color.BLACK);
            setBackground(new Color(153, 204, 255)); // latar normal
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    lbgambar.setIcon(icon);
    lbgambar.setText("");
}


private Image buatGambarTransparan(Image image, float opacity) {
    int width = image.getWidth(null);
    int height = image.getHeight(null);

    // Cek agar tidak error saat gambar belum ter-load
    if (width <= 0 || height <= 0) {
        return image; // kembalikan gambar asli jika error
    }

    BufferedImage buffered = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2d = buffered.createGraphics();
    g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacity));
    g2d.drawImage(image, 0, 0, null);
    g2d.dispose();

    return buffered;
}

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbgambar = new javax.swing.JLabel();
        lbharga = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        btnbeli = new javax.swing.JButton();
        lbstok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(153, 255, 255));

        lbgambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbgambar.setText("jLabel1");
        lbgambar.setMaximumSize(new java.awt.Dimension(160, 160));
        lbgambar.setMinimumSize(new java.awt.Dimension(160, 160));
        lbgambar.setPreferredSize(new java.awt.Dimension(160, 160));

        lbharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbharga.setText("Harga");

        lbnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbnama.setText("Nama");

        btnbeli.setText("Beli");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });

        lbstok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbstok.setText("Stok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbgambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnbeli)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbnama)
                .addGap(10, 10, 10)
                .addComponent(lbharga)
                .addGap(10, 10, 10)
                .addComponent(lbstok)
                .addGap(10, 10, 10)
                .addComponent(btnbeli)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
    try {
        if (CustomerLogin.sessionCustomer == null) {
            JOptionPane.showMessageDialog(this, "Silakan login terlebih dahulu.");
            return;
        }

        String customerId = CustomerLogin.sessionCustomer.getId();
        String namaProduk = lbnama.getText();
        long hargaSatuan = Long.parseLong(
            lbharga.getText().replace("Rp", "").replace(".", "").trim()
        );

        // Minta input jumlah pembelian dari user
        String inputJumlah = JOptionPane.showInputDialog(this, "Masukkan jumlah pembelian:");
        if (inputJumlah == null || inputJumlah.trim().isEmpty()) return;

        int jumlah = Integer.parseInt(inputJumlah.trim());
        if (jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0.");
            return;
        }

        String produkId;
        int stokTersedia;

        try (Connection conn = DBKoneksi.getConnection();
             PreparedStatement ps = conn.prepareStatement(
                 "SELECT id_produk, stok FROM produk WHERE nama = ?"
             )) {
            ps.setString(1, namaProduk);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    produkId = rs.getString("id_produk");
                    stokTersedia = rs.getInt("stok");
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Produk \"" + namaProduk + "\" tidak ditemukan."
                    );
                    return;
                }
            }
        }

        // 🔍 Cek jumlah sebelumnya yang sudah dibeli dalam transaksi pending
        int jumlahSebelumnya = 0;
        try (Connection conn = DBKoneksi.getConnection();
            PreparedStatement ps = conn.prepareStatement(
                "SELECT dt.jumlah_barang " +
                "FROM detail_transaksi dt " +
                "JOIN pembayaran p ON dt.pembayaran_order_id = p.order_id " +
                "JOIN transaksi t ON dt.transaksi_id_transaksi = t.id_transaksi " +
                "WHERE p.status = 'pending' AND t.customer_id = ? AND dt.produk_id_produk = ?"
            )) {
           ps.setString(1, customerId);
           ps.setString(2, produkId);
           try (ResultSet rs = ps.executeQuery()) {
               while (rs.next()) {
                   jumlahSebelumnya += rs.getInt("jumlah_barang");
               }
           }
       }

        int totalJumlahAkanDibeli = jumlah + jumlahSebelumnya;

        if (totalJumlahAkanDibeli > stokTersedia) {
            JOptionPane.showMessageDialog(this,
                "Stok tidak mencukupi.\n" +
                "Jumlah sebelumnya: " + jumlahSebelumnya + "\n" +
                "Jumlah baru: " + jumlah + "\n" +
                "Total: " + totalJumlahAkanDibeli + "\n" +
                "Stok tersedia: " + stokTersedia
            );
            return;
        }

        long totalHarga = hargaSatuan * jumlah;
        CustomerTransaksiOnline.prosesBeliProduk(customerId, produkId, hargaSatuan, jumlah, totalHarga);

    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka.");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Gagal memproses pembelian:\n" + ex.getMessage()
        );
    }
    }//GEN-LAST:event_btnbeliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.JLabel lbgambar;
    private javax.swing.JLabel lbharga;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbstok;
    // End of variables declaration//GEN-END:variables
}
