/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomerView;
import Koneksi.DBKoneksi;
import CustomerController.CustomerKeranjang;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AGIL
 */
public class TransaksiCustomer extends javax.swing.JPanel {

    /**
     * Creates new form TransaksiCustomer
     */
    public TransaksiCustomer() {
        initComponents();
        loadKeranjang();
    }
    
   
private void loadKeranjang() {
    try (Connection conn = Koneksi.DBKoneksi.getConnection()) {
        String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();

        String sql = """
            SELECT 
                p.nama AS nama_produk,
                dk.kategori,
                du.ukuran,
                dt.harga,
                dt.jumlah_barang,
                dt.total_harga
            FROM detail_transaksi dt
            JOIN transaksi t ON dt.transaksi_id_transaksi = t.id_transaksi
            JOIN produk p ON dt.produk_id_produk = p.id_produk
            JOIN detail_kategori dk ON p.detail_kategori_id_kategori = dk.id_kategori
            JOIN detail_ukuran du ON p.detail_ukuran_id_ukuran = du.id_ukuran
            JOIN pembayaran pb ON dt.pembayaran_order_id = pb.order_id
            WHERE t.customer_id = ? AND pb.status = 'pending'
            ORDER BY dt.transaksi_id_transaksi
        """;

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, customerId);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tabelkeranjang.getModel();
        model.setRowCount(0); // reset tabel

        int no = 1;
        int totalItem = 0;
        int totalBarang = 0;
        long totalHarga = 0;

        while (rs.next()) {
            int jumlah = rs.getInt("jumlah_barang");
            long total = rs.getLong("total_harga");

            Object[] row = {
                no++,
                rs.getString("nama_produk"),
                rs.getString("kategori"),
                rs.getString("ukuran"),
                rs.getLong("harga"),
                jumlah,
                total
            };
            model.addRow(row);

            totalItem++;
            totalBarang += jumlah;
            totalHarga += total;
        }

        txtjumlahitem.setText("Jumlah Item " + String.valueOf(totalItem));
        txttotalbarang.setText("Total Barang " + String.valueOf(totalBarang));
        txttotal.setText("Rp " + String.format("%,d", totalHarga).replace(',', '.') + ",00");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat keranjang: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkeranjang = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtjumlahitem = new javax.swing.JLabel();
        txttotalbarang = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        pilihanbayar = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnbayar = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("TRANSACTION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        tabelkeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Produk  ", "Kategori", "Ukuran ", "Harga", "Jumlah", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelkeranjang.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelkeranjang);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        txtjumlahitem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtjumlahitem.setText("Jumlah Item");

        txttotalbarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttotalbarang.setText("Total Barang");

        txttotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttotal.setText("Total");

        pilihanbayar.setModel(new DefaultComboBoxModel<>(new String[]{
            "Pilih Metode Pembayaran",
            "Transfer Bank (bank_transfer)",
            "GoPay (gopay)",
            "Alfamart",
            "Indomaret",
            "Kartu Kredit (credit_card)"
        }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Metode Pembayaran");

        btnbayar.setText("Bayar Sekarang");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtjumlahitem, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttotalbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbayar)
                    .addComponent(pilihanbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal)
                    .addComponent(txtjumlahitem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttotalbarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihanbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnclear.setText("Hapus Keranjang");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Barang");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnupdate.setText("Update Jumlah");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btntambah.setText("Tambah Barang");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addGap(130, 130, 130)
                        .addComponent(btnupdate)
                        .addGap(130, 130, 130)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnclear))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
    String metodeBaru = (String) pilihanbayar.getSelectedItem();
    
    if (CustomerController.CustomerLogin.sessionCustomer == null) {
        JOptionPane.showMessageDialog(this, "Anda harus login terlebih dahulu.");
        return;
    }

    String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();

    try (Connection conn = Koneksi.DBKoneksi.getConnection()) {
        // 1. Ambil order pending
        String orderId = CustomerController.CustomerPembayaran.getOrderIdPendingByCustomer(conn, customerId);
        if (orderId == null) {
            JOptionPane.showMessageDialog(this, "Tidak ada transaksi pending.");
            return;
        }

        // 2. Cek stok per item langsung berdasarkan tabel produk
        String sqlCekStok = ""
            + "SELECT dp.jumlah_barang, p.stok, p.id_produk, p.nama "
            + "FROM detail_transaksi dp "
            + "JOIN produk p ON dp.produk_id_produk = p.id_produk "
            + "WHERE dp.pembayaran_order_id = ?";

        try (PreparedStatement ps = conn.prepareStatement(sqlCekStok)) {
            ps.setString(1, orderId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    int jumlah     = rs.getInt("jumlah_barang");
                    int stok       = rs.getInt("stok");
                    String idProduk   = rs.getString("id_produk");
                    String namaProduk = rs.getString("nama");

                    if (stok < jumlah) {
                        JOptionPane.showMessageDialog(this,
                            "Transaksi gagal. Stok produk tidak mencukupi.\n\n" +
                            "Detail Produk:\n" +
                            "ID Produk     : " + idProduk + "\n" +
                            "Nama Produk   : " + namaProduk + "\n" +
                            "Stok Saat Ini : " + stok + "\n" +
                            "Jumlah Dibeli : " + jumlah + "\n\n" +
                            "Silakan perbarui keranjang atau hubungi admin.",
                            "Stok Tidak Cukup",
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
        }

        // 3. Lanjut ke proses pembayaran
        String metodeLama = CustomerController.CustomerPembayaran.getMetodePembayaran(conn, orderId);
        String metodeMidtransBaru = CustomerController.CustomerPembayaran.mapMetodeToMidtrans(metodeBaru);
        if (metodeMidtransBaru == null) {
            JOptionPane.showMessageDialog(this, "Silakan pilih metode pembayaran yang valid.");
            return;
        }

        if (metodeLama == null) {
            // Belum pilih metode, set lalu proses
            CustomerController.CustomerPembayaran.setMetodePembayaranBaru(conn, orderId, metodeMidtransBaru);
            CustomerController.CustomerPembayaran.prosesMidtrans(conn, orderId, metodeBaru, true);
        } else if (metodeLama.equalsIgnoreCase(metodeMidtransBaru)) {
            // Metode sama, ulang proses
            CustomerController.CustomerPembayaran.prosesMidtrans(conn, orderId, metodeBaru, false);
        } else {
            // Ganti metode
            int confirm = JOptionPane.showConfirmDialog(this,
                "Metode pembayaran sebelumnya adalah '" + metodeLama + "'.\nGanti ke '" + metodeMidtransBaru + "'?",
                "Konfirmasi Ganti Metode", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String orderIdBaru = CustomerController.CustomerPembayaran.generateOrderIdWithTimestamp();
                boolean updated = CustomerController.CustomerPembayaran.updateMetodeDanOrderId(conn, orderId, orderIdBaru, metodeMidtransBaru);
                if (!updated) {
                    JOptionPane.showMessageDialog(this, "Gagal update metode dan order ID.");
                    return;
                }
                CustomerController.CustomerPembayaran.prosesMidtrans(conn, orderIdBaru, metodeBaru, true);
            } else {
                CustomerController.CustomerPembayaran.prosesMidtrans(conn, orderId, metodeLama, false);
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       int confirm = JOptionPane.showConfirmDialog(this, "Hapus semua item dari keranjang?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();
            try {
                boolean sukses = CustomerKeranjang.hapusSemua(customerId);
                if (sukses) {
                    JOptionPane.showMessageDialog(this, "Semua item berhasil dihapus.");
                    loadKeranjang();
                } else {
                    JOptionPane.showMessageDialog(this, "Keranjang sudah kosong atau tidak ada transaksi pending.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
       int row = tabelkeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu produk yang ingin dihapus.");
            return;
        }

        String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Hapus produk '" + namaProduk + "' dari keranjang?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();

            try (Connection conn = DBKoneksi.getConnection()) {
                String sql = "SELECT id_produk FROM produk WHERE nama = ?";
                String produkId = "";
                try (PreparedStatement ps = conn.prepareStatement(sql)) {
                    ps.setString(1, namaProduk);
                    try (ResultSet rs = ps.executeQuery()) {
                        if (rs.next()) {
                            produkId = rs.getString("id_produk");
                        }
                    }
                }

                if (!produkId.isEmpty()) {
                    boolean sukses = CustomerKeranjang.hapusItem(customerId, produkId);
                    if (sukses) {
                        JOptionPane.showMessageDialog(this, "Produk berhasil dihapus.");
                        loadKeranjang();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal menghapus produk.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "ID produk tidak ditemukan.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int row = tabelkeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu produk yang mau diupdate.");
            return;
        }

        String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();
        String produkId = "";

        try (Connection conn = DBKoneksi.getConnection()) {
            String sql = "SELECT id_produk, stok FROM produk WHERE nama = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, namaProduk);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        produkId = rs.getString("id_produk");
                        int stok = rs.getInt("stok");

                        String input = JOptionPane.showInputDialog(this, "Masukkan jumlah baru (maks: " + stok + "):");
                        if (input == null) return;

                        int jumlahBaru;
                        try {
                            jumlahBaru = Integer.parseInt(input);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Input jumlah tidak valid.");
                            return;
                        }

                        if (jumlahBaru <= 0 || jumlahBaru > stok) {
                            JOptionPane.showMessageDialog(this, "Jumlah tidak boleh 0 atau melebihi stok.");
                            return;
                        }

                        int confirm = JOptionPane.showConfirmDialog(this, "Update jumlah ke " + jumlahBaru + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                        if (confirm == JOptionPane.YES_OPTION) {
                            String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();
                            boolean sukses = CustomerKeranjang.updateJumlahBarang(customerId, produkId, jumlahBaru);
                            if (sukses) {
                                loadKeranjang();
                            } else {
                                JOptionPane.showMessageDialog(this, "Gagal update jumlah.");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        int row = tabelkeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu barangnya.");
            return;
        }

        String namaProduk = tabelkeranjang.getValueAt(row, 1).toString();
        String produkId = "";

        try (Connection conn = DBKoneksi.getConnection()) {
            String sql = "SELECT id_produk FROM produk WHERE nama = ?";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, namaProduk);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        produkId = rs.getString("id_produk");
                    }
                }
            }

            if (produkId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Tambah 1 barang untuk \"" + namaProduk + "\"?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String customerId = CustomerController.CustomerLogin.sessionCustomer.getId();
                boolean berhasil = CustomerKeranjang.tambahJumlahBarang(customerId, produkId);
                if (berhasil) {
                    loadKeranjang();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambah. Stok sudah habis.", "Stok Limit", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btntambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pilihanbayar;
    private javax.swing.JTable tabelkeranjang;
    private javax.swing.JLabel txtjumlahitem;
    private javax.swing.JLabel txttotal;
    private javax.swing.JLabel txttotalbarang;
    // End of variables declaration//GEN-END:variables
}
